import type { Listing, Review, Guide } from './types'

export const guides: Guide[] = [
  {
    id: 'g1',
    name: 'Ram Bahadur Thapa',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop',
    rating: 4.9,
    reviewCount: 142,
    experienceYears: 8,
    languages: ['English', 'Nepali', 'Hindi'],
    badges: { govId: true, firstAid: true, cooperative: true, policeCheck: true },
    bio: 'Born in Sindhupalchok, I have guided treks to Panch Pokhari and surrounding sacred valleys for 8 years. I know every trail, spring, and shrine.',
    tripsCompleted: 320,
  },
  {
    id: 'g2',
    name: 'Mingma Sherpa',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop',
    rating: 4.8,
    reviewCount: 98,
    experienceYears: 12,
    languages: ['English', 'Nepali', 'Tibetan'],
    badges: { govId: true, firstAid: true, cooperative: true, policeCheck: false },
    bio: 'Raised in a Sherpa family in the Khumbu valley, I specialize in remote high-altitude routes away from the Everest crowds.',
    tripsCompleted: 480,
  },
  {
    id: 'g3',
    name: 'Sita Gurung',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&h=120&fit=crop',
    rating: 4.9,
    reviewCount: 89,
    experienceYears: 6,
    languages: ['English', 'Nepali'],
    badges: { govId: true, firstAid: true, cooperative: true, policeCheck: true },
    bio: 'I run my family homestay on Khopra Ridge and offer stays with home-cooked meals, mountain views, and stories passed through generations.',
    tripsCompleted: 0,
  },
]

export const listings: Listing[] = [
  {
    id: 'l1',
    type: 'trek',
    title: 'Panch Pokhari Trek',
    slug: 'panch-pokhari-trek',
    region: 'Bagmati',
    district: 'Sindhupalchok',
    description:
      'A remote 6-day trek to five sacred glacial lakes nestled above 4,000m in the hills of Sindhupalchok. Very few tourists reach this valley — you will share it only with yak herders and pilgrims. The trail winds through rhododendron forests, high alpine meadows, and past ancient stone shrines.',
    images: [
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=500&fit=crop',
    ],
    guide: guides[0],
    rating: 4.9,
    reviewCount: 142,
    difficulty: 'moderate',
    durationDays: 6,
    maxGroupSize: 6,
    maxAltitudeM: 4100,
    pricePerPerson: 350,
    currency: 'USD',
    included: ['Licensed guide', 'Trekking permits', 'Teahouse accommodation', 'Breakfast & dinner'],
    excluded: ['Travel insurance', 'Personal gear', 'Drinks & snacks', 'Tips'],
    culturalNote: 'These are sacred Hindu-Buddhist lakes. No swimming, no littering near the shrines. Cover shoulders when passing temples.',
    bestMonths: ['Oct', 'Nov', 'Mar', 'Apr'],
    tags: ['Sacred sites', 'High altitude', 'Remote', 'Pilgrimage'],
    isHiddenGem: true,
    isFeatured: true,
    latitude: 27.93,
    longitude: 85.77,
  },
  {
    id: 'l2',
    type: 'homestay',
    title: "Sita's Homestay — Khopra Ridge",
    slug: 'sitas-homestay-khopra-ridge',
    region: 'Gandaki',
    district: 'Kaski',
    description:
      'Stay with Sita\'s family in a traditional stone house perched on Khopra Ridge at 3,660m. Wake to direct views of Dhaulagiri and Nilgiri. Sita prepares all meals from her garden — organic dal bhat, seasonal vegetables, and fresh milk from the family\'s cows. This is village life, unchanged for generations.',
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?w=800&h=500&fit=crop',
    ],
    guide: guides[2],
    rating: 4.8,
    reviewCount: 89,
    pricePerPerson: 12,
    currency: 'USD',
    included: ['Private room', 'Breakfast & dinner', 'Hot shower', 'Village walk'],
    excluded: ['Alcohol', 'Laundry', 'Tips'],
    culturalNote: 'Remove shoes before entering the house. Ask before photographing family members. Meals are served at set times.',
    bestMonths: ['Oct', 'Nov', 'Dec', 'Mar', 'Apr', 'May'],
    tags: ['Mountain views', 'Family stay', 'Organic food', 'Peaceful'],
    isHiddenGem: true,
    latitude: 28.53,
    longitude: 83.69,
  },
  {
    id: 'l3',
    type: 'trek',
    title: 'Tamang Heritage Trail',
    slug: 'tamang-heritage-trail',
    region: 'Bagmati',
    district: 'Rasuwa',
    description:
      'A 5-day cultural immersion through Tamang villages in Rasuwa district. Visit ancient gompas, watch traditional weaving, share meals with Tamang families, and cross high passes with views of Langtang Himal. Far fewer trekkers than the main Langtang Valley route, yet equally spectacular.',
    images: [
      'https://images.unsplash.com/photo-1562778612-e1e0cda9915c?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1518544866330-95a2ab4e7482?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1498659911133-a2353fdc1468?w=800&h=500&fit=crop',
    ],
    guide: guides[1],
    rating: 4.7,
    reviewCount: 56,
    difficulty: 'easy',
    durationDays: 5,
    maxGroupSize: 8,
    maxAltitudeM: 3750,
    pricePerPerson: 280,
    currency: 'USD',
    included: ['Licensed guide', 'Homestay nights', 'All meals', 'Cultural program'],
    excluded: ['Transport to trailhead', 'Personal gear', 'Insurance'],
    culturalNote: 'Clockwise around mani walls and stupas. Ask permission before entering a gompa. Dress modestly in villages.',
    bestMonths: ['Mar', 'Apr', 'May', 'Oct', 'Nov'],
    tags: ['Culture', 'Villages', 'Gompa', 'Easy terrain'],
    isHiddenGem: true,
    latitude: 28.19,
    longitude: 85.31,
  },
  {
    id: 'l4',
    type: 'experience',
    title: 'Organic Farm Lunch & Cooking Class — Tansen',
    slug: 'organic-farm-lunch-tansen',
    region: 'Lumbini',
    district: 'Palpa',
    description:
      'Spend a morning on an organic hilltop farm in the medieval town of Tansen. Help harvest seasonal vegetables, grind spices on a traditional stone mill, and cook a full Newari meal from scratch. Eat together with the host family. Tansen is one of Nepal\'s most beautiful Newari towns and almost no package tours visit here.',
    images: [
      'https://images.unsplash.com/photo-1464454709131-ffd692591ee5?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=500&fit=crop',
    ],
    guide: guides[2],
    rating: 5.0,
    reviewCount: 34,
    durationDays: 1,
    maxGroupSize: 4,
    pricePerPerson: 35,
    currency: 'USD',
    included: ['Farm tour', 'Cooking class', 'Full Newari lunch', 'Recipe booklet'],
    excluded: ['Transport', 'Drinks'],
    culturalNote: 'Wash hands before cooking. Shoes off inside the kitchen. The family may offer raksi (local spirit) — politely declining is fine.',
    bestMonths: ['Jan', 'Feb', 'Mar', 'Sep', 'Oct', 'Nov', 'Dec'],
    tags: ['Food', 'Culture', 'Day trip', 'Newari'],
    latitude: 27.87,
    longitude: 83.54,
  },
  {
    id: 'l5',
    type: 'trek',
    title: 'Upper Dolpa Hidden Lakes Trek',
    slug: 'upper-dolpa-hidden-lakes',
    region: 'Karnali',
    district: 'Dolpa',
    description:
      'One of Nepal\'s most remote and least visited trekking regions. Upper Dolpa shares the Tibetan plateau landscape — dramatic eroded cliffs, turquoise lakes, ancient Bon monasteries, and sky-blue skies 365 days a year. This 12-day route takes you to lakes rarely seen by foreign visitors, staying with local families in villages untouched by tourism infrastructure.',
    images: [
      'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800&h=500&fit=crop',
    ],
    guide: guides[1],
    rating: 4.9,
    reviewCount: 21,
    difficulty: 'hard',
    durationDays: 12,
    maxGroupSize: 4,
    maxAltitudeM: 5360,
    pricePerPerson: 1200,
    currency: 'USD',
    included: ['Experienced guide', 'Porter', 'All permits', 'Accommodation', 'All meals'],
    excluded: ['Flights to Juphal', 'Insurance', 'Personal gear'],
    culturalNote: 'Upper Dolpa is a restricted area with special permits. Bon monastery etiquette differs from Buddhist — circle shrines anticlockwise. No photos inside monasteries.',
    bestMonths: ['Jun', 'Jul', 'Aug', 'Sep'],
    tags: ['Remote', 'Tibet-like', 'Expert', 'Restricted area', 'Monastery'],
    isHiddenGem: true,
    latitude: 29.17,
    longitude: 82.96,
  },
]

export const reviews: Review[] = [
  { id: 'r1', listingId: 'l1', travelerName: 'Sarah Chen', travelerCountry: 'UK', rating: 5, comment: 'Incredible offbeat trek. Ram knew every shrine and story. The lakes at sunset were beyond words. No other tourists the entire trip!', date: 'Mar 2026', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=60&h=60&fit=crop' },
  { id: 'r2', listingId: 'l1', travelerName: 'Tom Eriksen', travelerCountry: 'Norway', rating: 5, comment: 'Ram is the best guide I\'ve had in 20 years of trekking. Organised, knowledgeable, great cook. Panch Pokhari is a hidden gem.', date: 'Feb 2026', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop' },
  { id: 'r3', listingId: 'l1', travelerName: 'Priya Nair', travelerCountry: 'India', rating: 5, comment: 'As a solo female traveler I was slightly nervous, but Ram made me feel completely safe. The daily log feature so my parents could see I was ok was reassuring.', date: 'Jan 2026', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop' },
  { id: 'r4', listingId: 'l2', travelerName: 'Marco Russo', travelerCountry: 'Italy', rating: 5, comment: 'Sita\'s dal bhat changed my life. The views of Dhaulagiri from the bedroom window every morning. Simple, pure, perfect.', date: 'Nov 2025', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop' },
  { id: 'r5', listingId: 'l2', travelerName: 'Anna Kowalski', travelerCountry: 'Poland', rating: 5, comment: 'Best accommodation decision of my Nepal trip. Khopra Ridge feels like a secret the internet hasn\'t found yet.', date: 'Oct 2025', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=60&h=60&fit=crop' },
  { id: 'r6', listingId: 'l3', travelerName: 'James Wu', travelerCountry: 'USA', rating: 5, comment: 'Mingma was excellent. The Tamang Heritage Trail had more cultural depth than anything we saw on the Annapurna Circuit.', date: 'Apr 2026', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop' },
]

export function getListing(slug: string): Listing | undefined {
  return listings.find((l) => l.slug === slug)
}

export function getListingReviews(listingId: string): Review[] {
  return reviews.filter((r) => r.listingId === listingId)
}

export const ADDONS = [
  { id: 'porter',   label: 'Porter',              price: 10, unit: '/day', description: 'Carries up to 25 kg of gear' },
  { id: 'sleeping', label: 'Sleeping bag rental',  price: 15, unit: ' total', description: 'High-altitude rated, −10°C' },
  { id: 'cooking',  label: 'Cooking class',        price: 20, unit: ' total', description: 'Learn to cook dal bhat with host' },
  { id: 'sat',      label: 'Satellite messenger',  price: 30, unit: ' total', description: 'Garmin inReach rental' },
]

export const PAYMENT_METHODS = [
  { id: 'card',     label: 'Credit / Debit card',    sub: 'Visa, Mastercard, Amex' },
  { id: 'esewa',    label: 'eSewa',                   sub: 'Nepal digital wallet' },
  { id: 'khalti',   label: 'Khalti',                  sub: 'Nepal digital wallet' },
  { id: 'bank',     label: 'Bank transfer',           sub: 'Details sent on confirmation' },
  { id: 'arrival',  label: 'Pay on arrival',          sub: 'Cash only · Remote areas' },
]
